/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import com.mxrck.autocompleter.TextAutoCompleter;
import ec.edu.ups.controlador.ControladorTicket;
import ec.edu.ups.modelo.ExpresionRegular;
import ec.edu.ups.modelo.HiloMovimiento;
import ec.edu.ups.modelo.Persona;
import ec.edu.ups.modelo.Tarifa;
import ec.edu.ups.modelo.Ticket;
import ec.edu.ups.modelo.ValidarSesion;
import ec.edu.ups.modelo.Vehiculo;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.JLabel;

/**
 *
 * @author Paul Idrovo
 */
public class VistaCliente extends javax.swing.JFrame {

    private TextAutoCompleter cedulasAt;
    private TextAutoCompleter placasAt;
    private TextAutoCompleter marcasAt;
    private TextAutoCompleter colorAt;
    private int parqueaderoId;
    private boolean cedulaExistente;
    private boolean vehiculoExistente;

    private VistaParqueaderos vistaParqueaderos;

    public VistaCliente(VistaParqueaderos vistaParqueaderos, int parqueadero) {
        initComponents();
        Tarifa tarifa = new Tarifa();
        cedulaExistente = false;
        vehiculoExistente = false;
        List<Tarifa> listaTarifas = tarifa.TarifasMembresia();
        lblHoraT.setText(listaTarifas.get(0).getValorTarifa() + "");
        lblDiaT.setText(listaTarifas.get(1).getValorTarifa() + "");
        lblSemanaT.setText(listaTarifas.get(2).getValorTarifa() + "");
        lblMesT.setText(listaTarifas.get(3).getValorTarifa() + "");

        this.parqueaderoId = parqueadero;
        this.vistaParqueaderos = vistaParqueaderos;
        this.vistaParqueaderos.setEnabled(false);
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/ec/edu/ups/iconos/Icono.png")).getImage());
        this.setResizable(false);

        Persona cedulas = new Persona();
        cedulasAt = new TextAutoCompleter(txtCedula);
        cedulas.getPersonas().forEach(p -> {
            cedulasAt.addItem(p.getCedula());
        });
        Vehiculo vehiculo = new Vehiculo();
        marcasAt = new TextAutoCompleter(txtMarca);
        for (Vehiculo vh : vehiculo.getMarcas()) {
            marcasAt.addItem(vh.getMarca());
        }
        colorAt = new TextAutoCompleter(txtColor);
        for (Vehiculo vh : vehiculo.getColores()) {
            colorAt.addItem(vh.getColor());
        }

        pnlTarifas.setVisible(false);
        lblCedulaId.setVisible(false);
        lblPlacaId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo = new javax.swing.ButtonGroup();
        periodo = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        rbtnRegular = new javax.swing.JRadioButton();
        rbtnArrendamiento = new javax.swing.JRadioButton();
        pnlTarifas = new javax.swing.JPanel();
        rbnDia = new javax.swing.JRadioButton();
        rbnSemana = new javax.swing.JRadioButton();
        rbnMes = new javax.swing.JRadioButton();
        spnCantidad = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        rbnHora = new javax.swing.JRadioButton();
        lblHoraT = new javax.swing.JLabel();
        lblDiaT = new javax.swing.JLabel();
        lblSemanaT = new javax.swing.JLabel();
        lblMesT = new javax.swing.JLabel();
        lblPlacaId = new javax.swing.JLabel();
        lblCedulaId = new javax.swing.JLabel();
        ckFinal = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO TICKET"));

        jLabel7.setText("CEDULA");

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        jLabel8.setText("NOMBRE");

        txtNombre.setEnabled(false);

        jLabel9.setText("APELLIDO");

        txtApellido.setEnabled(false);

        jLabel10.setText("DIRECCION");

        txtDireccion.setEnabled(false);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/ticket.png"))); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel11.setText("TELEFONO");

        txtTelefono.setEnabled(false);

        jLabel12.setText("PLACA");

        jLabel13.setText("MARCA");

        jLabel14.setText("COLOR");

        txtMarca.setEnabled(false);

        txtPlaca.setEnabled(false);
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });

        txtColor.setEnabled(false);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/cancelar.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tipo.add(rbtnRegular);
        rbtnRegular.setText("P. REGULAR");
        rbtnRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRegularActionPerformed(evt);
            }
        });

        tipo.add(rbtnArrendamiento);
        rbtnArrendamiento.setText("P. ARRENDAMIENTO");
        rbtnArrendamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnArrendamientoActionPerformed(evt);
            }
        });

        periodo.add(rbnDia);
        rbnDia.setText("DIA");

        periodo.add(rbnSemana);
        rbnSemana.setText("SEMANA");

        periodo.add(rbnMes);
        rbnMes.setText("MES");

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel1.setText("CANTIDAD:");

        periodo.add(rbnHora);
        rbnHora.setText("HORA");

        lblHoraT.setText("jLabel2");

        lblDiaT.setText("jLabel2");

        lblSemanaT.setText("jLabel2");

        lblMesT.setText("jLabel2");

        javax.swing.GroupLayout pnlTarifasLayout = new javax.swing.GroupLayout(pnlTarifas);
        pnlTarifas.setLayout(pnlTarifasLayout);
        pnlTarifasLayout.setHorizontalGroup(
            pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarifasLayout.createSequentialGroup()
                .addGroup(pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTarifasLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addGroup(pnlTarifasLayout.createSequentialGroup()
                        .addGroup(pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTarifasLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblHoraT, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTarifasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbnHora, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiaT, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarifasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSemanaT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTarifasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rbnSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMesT, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbnMes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlTarifasLayout.setVerticalGroup(
            pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarifasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraT)
                    .addComponent(lblDiaT)
                    .addComponent(lblSemanaT)
                    .addComponent(lblMesT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rbnSemana)
                    .addComponent(rbnMes)
                    .addComponent(rbnHora)
                    .addComponent(rbnDia))
                .addGap(18, 18, 18)
                .addGroup(pnlTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblPlacaId.setText("0");

        lblCedulaId.setText("0");

        ckFinal.setText("CONS. FINAL");
        ckFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckFinalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(55, 55, 55)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtDireccion)
                    .addComponent(txtApellido)
                    .addComponent(txtTelefono)
                    .addComponent(txtPlaca)
                    .addComponent(txtMarca)
                    .addComponent(txtColor)
                    .addComponent(txtNombre))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pnlTarifas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(rbtnRegular)
                                .addGap(83, 83, 83)
                                .addComponent(rbtnArrendamiento)
                                .addGap(97, 97, 97))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(140, 140, 140)
                                .addComponent(btnCancelar)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(lblPlacaId))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCedulaId)))
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckFinal))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnRegular)
                    .addComponent(rbtnArrendamiento))
                .addGap(18, 18, 18)
                .addComponent(pnlTarifas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar)
                            .addComponent(btnRegistrar))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCedulaId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlacaId)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        ValidarSesion vs = ValidarSesion.getValidarSesion(0, "");
        ControladorTicket controladorTicket = new ControladorTicket();
        String tipoTicket;
        double valorTicket = 0;
        int idsalida = 0;
        int personaId = 0;
        int placaId = 0;
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        String fechaEntrada = "'" + simpleDateFormat.format(new Date()) + "'";
        String fechaSalida = null;
        if (!cedulaExistente) {
            Persona pr = new Persona(txtCedula.getText(), txtNombre.getText(), txtApellido.getText(), txtDireccion.getText(), txtTelefono.getText());
            pr.crearPersona(pr);
            personaId = pr.idPersona(txtCedula.getText());
        }
        if (!vehiculoExistente) {
            Vehiculo vh = new Vehiculo(txtPlaca.getText(), txtMarca.getText(), txtColor.getText(), personaId);
            vh.crearVehiculo(vh);
            placaId = vh.idVehiculo(txtPlaca.getText());
        } else {
            placaId = Integer.parseInt(lblPlacaId.getText());
        }
        if (rbtnRegular.isSelected()) {
            tipoTicket = "REGULAR";
        } else {
            tipoTicket = "ARRENDAMIENTO";
            idsalida = vs.getId();
            if (rbnHora.isSelected()) {
                valorTicket = Double.parseDouble(lblHoraT.getText()) * (int) spnCantidad.getValue();
                Calendar ahora = Calendar.getInstance();
                ahora.add(Calendar.HOUR, (int) spnCantidad.getValue());
                fechaSalida = "'" + simpleDateFormat.format(ahora.getTime()) + "'";;
            } else if (rbnDia.isSelected()) {
                valorTicket = Double.parseDouble(lblDiaT.getText()) * (int) spnCantidad.getValue();
                Calendar ahora = Calendar.getInstance();
                ahora.add(Calendar.DAY_OF_YEAR, (int) spnCantidad.getValue());
                fechaSalida = "'" + simpleDateFormat.format(ahora.getTime()) + "'";;
            } else if (rbnSemana.isSelected()) {
                valorTicket = Double.parseDouble(lblSemanaT.getText()) * (int) spnCantidad.getValue();
                Calendar ahora = Calendar.getInstance();
                ahora.add(Calendar.DAY_OF_YEAR, (int) spnCantidad.getValue() * 7);
                fechaSalida = "'" + simpleDateFormat.format(ahora.getTime()) + "'";;
            } else if (rbnMes.isSelected()) {
                valorTicket = Double.parseDouble(lblMesT.getText()) * (int) spnCantidad.getValue();
                Calendar ahora = Calendar.getInstance();
                ahora.add(Calendar.MONTH, (int) spnCantidad.getValue());
                fechaSalida = "'" + simpleDateFormat.format(ahora.getTime()) + "'";;
            }
        }
        boolean guardar = true;
        if (valorTicket != 0.00) {
            DecimalFormat df = new DecimalFormat("#.00");
            int confirmado = JOptionPane.showConfirmDialog(null, "EL VALOR A PAGAR ES DE $" + df.format(valorTicket) + " CONTINUAR ?");

            if (JOptionPane.OK_OPTION != confirmado) {
                guardar = false;
            }
        }
        if (guardar) {
            controladorTicket.crearTicket(new Ticket(tipoTicket, fechaEntrada, fechaSalida, valorTicket, placaId, parqueaderoId, vs.getId(), idsalida));
            List<JLabel> lblParqueadero = this.vistaParqueaderos.getLblParqueaderos();
            parqueaderoId--;
            var thread = new Thread(new HiloMovimiento(vistaParqueaderos, parqueaderoId));
            thread.start();
            //lblParqueadero.get(parqueaderoId).setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/iconos/v" + this.vistaParqueaderos.getValorDado() + ".png")));
            this.vistaParqueaderos.setLblParqueaderos(lblParqueadero);
            this.vistaParqueaderos.setEnabled(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char validar = evt.getKeyChar();
        int asscii = (int) validar;
        if (!Character.isDigit(validar) && validar != '\n' && asscii != 8 && validar != '') {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "INGRESE SOLO NUMEROS", "ERROR DE DATOS", JOptionPane.WARNING_MESSAGE);
        }
        if (validar == '\n') {
            Persona p = new Persona();
            p = p.getPersona(txtCedula.getText());
            if (p == null || p.getCedula() == null) {
                JOptionPane.showMessageDialog(null, "PERSONA NO REGISTRADA", "INFORMACION", 1);
                txtNombre.setEnabled(true);
                txtApellido.setEnabled(true);
                txtDireccion.setEnabled(true);
                txtTelefono.setEnabled(true);
                txtNombre.setText("");
                txtApellido.setText("");
                txtDireccion.setText("");
                txtTelefono.setText("");
                cedulaExistente = false;
            } else {
                txtNombre.setText(p.getNombre());
                txtApellido.setText(p.getApellido());
                txtDireccion.setText(p.getDireccion());
                txtTelefono.setText(p.getTelefono());
                Vehiculo vehiculo = new Vehiculo();
                placasAt = new TextAutoCompleter(txtPlaca);
                vehiculo.getPlacasCedula(p.getId()).forEach(vh -> {
                    placasAt.addItem(vh.getPlaca());
                });
                lblCedulaId.setText(p.getId() + "");
                cedulaExistente = true;
            }
            txtPlaca.setEnabled(true);
            txtPlaca.setText("");
        }

    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
        char validar = evt.getKeyChar();
        int asscii = (int) validar;
        if (validar == '\n') {
            ExpresionRegular exPlaca = new ExpresionRegular();
            exPlaca.ingresarRegex("^\\w{3}\\d{4}$");
            if (exPlaca.validar(txtPlaca.getText())) {
                Vehiculo vh = new Vehiculo();
                vh = vh.getVehiculo(txtPlaca.getText());
                if (vh == null || vh.getPlaca() == null) {
                    JOptionPane.showMessageDialog(null, "PLACA NO REGISTRADA", "INFORMACION", 1);
                    txtMarca.setEnabled(true);
                    txtColor.setEnabled(true);
                    txtMarca.setText("");
                    txtColor.setText("");
                    vehiculoExistente = false;
                } else {
                    txtMarca.setText(vh.getMarca());
                    txtColor.setText(vh.getColor());
                    lblPlacaId.setText(vh.getId() + "");
                    vehiculoExistente = true;
                }
            } else {
                JOptionPane.showMessageDialog(null, "PLACA NO VALIDA", "INFORMACION", 1);
            }
        }
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.vistaParqueaderos.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbtnRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRegularActionPerformed
        if (rbtnRegular.isSelected()) {
            pnlTarifas.setVisible(false);
        }
    }//GEN-LAST:event_rbtnRegularActionPerformed

    private void rbtnArrendamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnArrendamientoActionPerformed
        if (rbtnArrendamiento.isSelected()) {
            pnlTarifas.setVisible(true);
        }
    }//GEN-LAST:event_rbtnArrendamientoActionPerformed

    private void ckFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckFinalMouseClicked
        if (ckFinal.isSelected()) {
            txtCedula.setEnabled(false);
            txtCedula.setText("9999999999");
            Persona p = new Persona();
            p = p.getPersona(txtCedula.getText());
            txtNombre.setText("CONSUMIDOR FINAL");
            txtApellido.setText(" ");
            txtDireccion.setText("S/N");
            txtTelefono.setText("9999999999");
            txtPlaca.setEnabled(true);
            Vehiculo vehiculo = new Vehiculo();
            placasAt = new TextAutoCompleter(txtPlaca);
            vehiculo.getPlacasCedula(p.getId()).forEach(vh -> {
                placasAt.addItem(vh.getPlaca());
            });
        } else {
            txtCedula.setEnabled(true);
            txtNombre.setText("");
            txtApellido.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtPlaca.setEnabled(false);
        }
    }//GEN-LAST:event_ckFinalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox ckFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCedulaId;
    private javax.swing.JLabel lblDiaT;
    private javax.swing.JLabel lblHoraT;
    private javax.swing.JLabel lblMesT;
    private javax.swing.JLabel lblPlacaId;
    private javax.swing.JLabel lblSemanaT;
    private javax.swing.ButtonGroup periodo;
    private javax.swing.JPanel pnlTarifas;
    private javax.swing.JRadioButton rbnDia;
    private javax.swing.JRadioButton rbnHora;
    private javax.swing.JRadioButton rbnMes;
    private javax.swing.JRadioButton rbnSemana;
    private javax.swing.JRadioButton rbtnArrendamiento;
    private javax.swing.JRadioButton rbtnRegular;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.ButtonGroup tipo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
